sudo: required

language: bash

services:
  - docker

env:
  # Data Analytics
  - DH_REPO="cloudsuite/data-analytics" IMG_TAG="latest" DF_PATH="./benchmarks/data-analytics/"
  - DH_REPO="cloudsuite/data-analytics" IMG_TAG="data" DF_PATH="./benchmarks/data-analytics/dataset"
  # Data Caching
  - DH_REPO="cloudsuite/data-caching" IMG_TAG="server" DF_PATH="./benchmarks/data-caching/server"
  - DH_REPO="cloudsuite/data-caching" IMG_TAG="client" DF_PATH="./benchmarks/data-caching/client"
  # Data Serving
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="server" DF_PATH="./benchmarks/data-serving/server"
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="client" DF_PATH="./benchmarks/data-serving/client"
  # Graph Analytics
  # - DH_REPO="cloudsuite/graph-analytics" IMG_TAG="benchmark" DF_PATH="./benchmarks/graph-analytics/benchmark"
  # - DH_REPO="cloudsuite/graph-analytics" IMG_TAG="data" DF_PATH="./benchmarks/graph-analytics/data"
  # In-memory Analytics
  # Media Streaming
  # Spark Base
  # Web Search
  - DH_REPO="cloudsuite/web-search" IMG_TAG="server" DF_PATH="./benchmarks/web-search/server"
  - DH_REPO="cloudsuite/web-search" IMG_TAG="client" DF_PATH="./benchmarks/web-search/client"
  # - DH_REPO="cloudsuite/web-search" IMG_TAG="data" DF_PATH="./benchmarks/web-search/data"
  # Web Serving
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="db_server" DF_PATH="./benchmarks/web-serving/db_server"
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="faban_client" DF_PATH="./benchmarks/web-serving/faban_client"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="web_server" DF_PATH="./benchmarks/web-serving/web_server"
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="memcached_server" DF_PATH="./benchmarks/web-serving/memcached_server"

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"

script:
   - docker build -t $DH_REPO:$IMG_TAG $DF_PATH
   - docker push $DH_REPO;
