# Conversion
markdown:           kramdown
highlighter:        rouge
kramdown:
  input:            GFM


# Permalinks
permalink:        pretty

# Setup
title:            CloudSuite
tagline:          'A Benchmark Suite for Cloud Services'
description:      'A Benchmark Suite for Cloud Services'
url:              'http://cloudsuite.ch/'
baseurl:          '/'

author:
  name:           'CloudSuite'
  url:             http://cloudsuite.ch

paginate:         3
paginate_path:    blog/page:num

# Custom vars
version:          3.0
blog_path:        blog/
excerpt_separator: <!--more-->

github:
  repo:           https://github.com/ParsaLab/cloudsuite

# Handling Reading
exclude: 			 [old]

gems: [jekyll-paginate, jekyll-gist]
