# Permalinks
permalink:           pretty

# Setup
title:               CloudSuite
tagline:             'A Benchmark Suite for Cloud Services'
description:         'CloudSuite'
url:                 http://cloudsuite.ch
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              CloudSuite
  url:               https://cloudsuite.ch
  email:             cloudsuite@listes.epfl.ch

# Conversion
markdown:           kramdown
highlighter:        rouge
kramdown:
  input:            GFM

# Custom vars
version:             1.0.0

# Handling Reading
exclude: 			 [old]

gems:                [jekyll-paginate]
